# ollama
ollama:
  url: "http://localhost:11434/v1"
  host: "http://localhost:11434"
  model: "ministral-3:8b"
  timeout: 60.0

# mistral api
mistral:
  model: "mistral-small-2603"
  embed: "mistral-embed"
  api_key_env: "MISTRAL_API_KEY"

#neo4j
neo4j:
  user: "55b73bde"
  password_env: "neo4j_password"
  uri: "neo4j+s://55b73bde.databases.neo4j.io"

# file paths used for indexing
paths:
  # initial csv data
  csv: "resources/datasets/final_sample.csv"
  # processed csv data
  json: "resources/datasets/processed_volunteer_data.json"
  vectordb: "resources/vectordb"
  knowledge_graph: "resources/knowledge_graph"
  HFcache: "resources/HF_cache"
  reference_answers: "resources/datasets/reference_answers.json"
  sqlite: "resources/sqlite"

# determines which part of the application gets run
# indexing -> starts indexing phase
# rag -> starts the actual rag application
#mode: "indexing"
mode: "rag"

# determines if preprocessed data is reused or newly built
keep_data: true

# determines if vectordb is reused or newly built
keep_vectordb: true

# determines if knowledge graph is reused or newly built
keep_knowledge_graph: false

# determines if local mistral LLM is used or a larger LLM per API call
use_local_llm: false